#!/usr/bin/env bash
# Generates the Tauri updater manifest (latest.json) for a single build target.
#
# Usage: generate-latest-json.sh <rust-target> <git-ref-name> [bundle-dir]
#
# Invoked from the `frontend/` directory (both build jobs set
# `defaults.run.working-directory: frontend`), so the default bundle dir is
# resolved relative to that.
#
# Deliberately NO `set -e`. The signature lookup below relies on short-circuit
# chains such as `[ -z "$SIG_FILE" ] && SIG_FILE=$(find ...)`, which return
# non-zero whenever the variable is already set. Under errexit a perfectly
# healthy build would abort. A missing .sig is a warning, not a failure - the
# `::warning::` + `exit 0` path is intentional and must stay that way.

set -uo pipefail

TARGET="${1:?usage: generate-latest-json.sh <rust-target> <git-ref-name> [bundle-dir]}"
REF_NAME="${2:?usage: generate-latest-json.sh <rust-target> <git-ref-name> [bundle-dir]}"
BUNDLE_DIR="${3:-src-tauri/target/$TARGET/release/bundle}"

# The release is published to whichever repo the workflow runs in.
REPO="${GITHUB_REPOSITORY:-xinbaizhe/SelfEvolvingSkills}"

echo "=== DEBUG: bundle dir contents ==="
ls -laR "$BUNDLE_DIR/" 2>/dev/null || echo "(bundle dir not found)"

VERSION="$REF_NAME"
VERSION="${VERSION#v}"
echo "Version: $VERSION, Target: $TARGET"

# Map Rust target to Tauri platform key
case "$TARGET" in
  x86_64-pc-windows-msvc)    PLATFORM="windows-x86_64" ;;
  aarch64-pc-windows-msvc)   PLATFORM="windows-aarch64" ;;
  x86_64-apple-darwin)       PLATFORM="darwin-x86_64" ;;
  aarch64-apple-darwin)      PLATFORM="darwin-aarch64" ;;
  x86_64-unknown-linux-gnu)  PLATFORM="linux-x86_64" ;;
  aarch64-unknown-linux-gnu) PLATFORM="linux-aarch64" ;;
  *) echo "Unknown target: $TARGET"; exit 1 ;;
esac
echo "Platform key: $PLATFORM"

# Find the updater artifact signature generated by Tauri.
# With createUpdaterArtifacts=true, Windows can reuse the signed NSIS .exe.
case "$TARGET" in
  *windows*)
    SIG_FILE=$(find "$BUNDLE_DIR" -name "*.exe.sig" -type f 2>/dev/null | head -1)
    [ -z "$SIG_FILE" ] && SIG_FILE=$(find "$BUNDLE_DIR" -name "*.nsis.zip.sig" -type f 2>/dev/null | head -1)
    [ -z "$SIG_FILE" ] && SIG_FILE=$(find "$BUNDLE_DIR" -name "*.msi.zip.sig" -type f 2>/dev/null | head -1)
    [ -z "$SIG_FILE" ] && SIG_FILE=$(find "$BUNDLE_DIR" -name "*.msi.sig" -type f 2>/dev/null | head -1)
    ;;
  *apple*)
    SIG_FILE=$(find "$BUNDLE_DIR" -name "*.app.tar.gz.sig" -type f 2>/dev/null | head -1)
    ;;
  *linux*)
    SIG_FILE=$(find "$BUNDLE_DIR" -name "*.AppImage.tar.gz.sig" -type f 2>/dev/null | head -1)
    [ -z "$SIG_FILE" ] && SIG_FILE=$(find "$BUNDLE_DIR" -name "*.AppImage.sig" -type f 2>/dev/null | head -1)
    [ -z "$SIG_FILE" ] && SIG_FILE=$(find "$BUNDLE_DIR" -name "*.deb.sig" -type f 2>/dev/null | head -1)
    ;;
  *)
    SIG_FILE=$(find "$BUNDLE_DIR" -name "*.sig" -type f 2>/dev/null | head -1)
    ;;
esac
if [ -z "$SIG_FILE" ]; then
  echo "::warning::No updater .sig found for $TARGET - updater artifacts not generated."
  echo "Ensure TAURI_SIGNING_PRIVATE_KEY is set and createUpdaterArtifacts is enabled."
  echo "=== DEBUG: searching for .sig in entire target dir ==="
  find src-tauri/target -name "*.sig" 2>/dev/null || echo "(none found)"
  exit 0
fi
SIGNATURE=$(cat "$SIG_FILE")
echo "Found signature: $SIG_FILE"

# Derive installer file from .sig file (strip .sig suffix)
INSTALLER_FILE="${SIG_FILE%.sig}"
if [ ! -f "$INSTALLER_FILE" ]; then
  echo "Installer file not found at $INSTALLER_FILE (from sig: $SIG_FILE)"
  echo "=== DEBUG: listing all bundle files ==="
  find "$BUNDLE_DIR" -type f 2>/dev/null | head -30
  exit 0
fi

FILENAME=$(basename "$INSTALLER_FILE")
RELEASE_FILENAME="${FILENAME// /.}"
export VERSION PLATFORM SIGNATURE RELEASE_FILENAME REPO
export PUB_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
export OUTFILE="$BUNDLE_DIR/latest.json"

# Without `set -e` these failures would otherwise be swallowed and the success
# message below would be printed over a file that was never written.
if ! command -v node >/dev/null 2>&1; then
  echo "::error::node is not on PATH - it is required to write latest.json (actions/setup-node provides it)"
  exit 1
fi

if ! node -e "
  const fs = require('fs')
  const encodedFilename = encodeURIComponent(process.env.RELEASE_FILENAME)
  const manifest = {
    version: process.env.VERSION,
    notes: '',
    pub_date: process.env.PUB_DATE,
    platforms: {
      [process.env.PLATFORM]: {
        signature: process.env.SIGNATURE,
        url: 'https://github.com/' + process.env.REPO + '/releases/download/v' + process.env.VERSION + '/' + encodedFilename
      }
    }
  }
  fs.writeFileSync(process.env.OUTFILE, JSON.stringify(manifest, null, 2))
"; then
  echo "::error::failed to write $OUTFILE"
  exit 1
fi

echo "Generated latest.json:"
cat "$OUTFILE"
